/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package virtual.pet.shelter;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class VirtualPetShelterTest {
    @Test 
    void appHasAGreeting() {
        VirtualPetShelter classUnderTest = new VirtualPetShelter();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
